lib/weatherdrobe_web/router.ex
defmodule WeatherdrobeWeb.Router do
  use WeatherdrobeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug WeatherdrobeWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WeatherdrobeWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/home", PageController, :home
    resources "/users", UserController
    resources "/outfits", OutfitController
    resources "/activities", ActivityController
    resources "/conjunctions", ConjunctionController
    resources "/calendars", CalendarController
    resources "/sessions", SessionController, only: [:create, :delete], singelton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", WeatherdrobeWeb do
  #   pipe_through :api
  # end
end

lib/weatherdrobe_web/views/shared_view.ex
defmodule WeatherdrobeWeb.SharedView do
  use WeatherdrobeWeb, :view
end

lib/weatherdrobe_web/templates/shared/_header.html.eex
<header>
  <section class="nav-bar">
    <nav role="navigation">
      <ul class="nav">
        <li class="nav">   <%= link "Sign In", to: "/", class: 'nav' %> </li>
        <li class="nav">   <%= link "Register", to: Routes.user_path(@conn, :new), class: 'nav' %> </li>
        <li class="nav">   <%= link "Users", to: Routes.user_path(@conn, :index), class: 'nav' %> </li>
        <li class="nav">   <%= link "Schedule", to: Routes.calendar_path(@conn, :index), class: 'nav' %> </li>
        <li class="nav">   <%= link "Wardrobe", to: Routes.outfit_path(@conn, :index), class: 'nav' %> </li>
        <li class="nav">   <%= link "Conjunction", to: Routes.conjunction_path(@conn, :index), class: 'nav' %> </li>
        <li class="nav">   <%= link "Activities", to: Routes.activity_path(@conn, :index), class: 'nav' %> </li>
        <li class="nav">   <%= link "Home", to: "/home", class: 'nav nav-left' %> </li>
      </ul>
    </nav>
  </section>
</header>